### ISSUE TITLE
binance APIError(code=-1003)

### ISSUE THREAD

**Issue by guibabtc** [CyberPunkMetalHead/Binance-volatility-trading-bot#105]
Traceback (most recent call last):
  File "Binance Detect Moonings.py", line 408, in <module>
    client = Client(access_key, secret_key)
  File "/home/guibabtc/bot/lib/python3.8/site-packages/binance/client.py", line 294, in __init__
    self.ping()
  File "/home/guibabtc/bot/lib/python3.8/site-packages/binance/client.py", line 520, in ping
    return self._get('ping', version=self.PRIVATE_API_VERSION)
  File "/home/guibabtc/bot/lib/python3.8/site-packages/binance/client.py", line 365, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/home/guibabtc/bot/lib/python3.8/site-packages/binance/client.py", line 328, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/guibabtc/bot/lib/python3.8/site-packages/binance/client.py", line 309, in _request
    return self._handle_response(self.response)
  File "/home/guibabtc/bot/lib/python3.8/site-packages/binance/client.py", line 318, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Way too much request weight used; IP banned until 1621207852808. Please use the websocket for live updates to avoid bans.

**Anyone know how  to add websocket?**

**Comment by Markkop** [comment]
Which params did you use? Perhaps we can find out which combination we can/can't use for a give number of MAX_COINS or check time interval

**Comment by guibabtc** [comment]
MAX_COINS: 9

TIME_DIFFERENCE: 3

RECHECK_INTERVAL: 36

**Comment by getsec** [comment]
You hit the API limit it looks like

**Comment by Markkop** [comment]
Your configs looks fine, idk why it hit the API Limit :thinking:

**Comment by FreshLondon** [comment]
I had the same yesterday, holding a bunch of coins and 13USDT remaining - bot would attempt to buy from 8 or so pairs and be rejected on each one (not enough USDT for minimum order in bot settings).

After numerous failures, Binance said 'enough is enough' and closed the connection.

Are balances monitored, does the bot poll for availability before placing an order?

**Comment by getsec** [comment]
#140 addresses the currency issue. Without knowing your config it would be hard to know exactly what happened here. If you experience this again, please open up another issue, also check out the discord.
