### ISSUE TITLE
Connection aborted.

### ISSUE THREAD

**Issue by MrPr0xY** [CyberPunkMetalHead/Binance-volatility-trading-bot#141]
Traceback (most recent call last):
  File "C:\Bot\venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Bot\venv\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Bot\venv\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Bot\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Bot\venv\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Bot\venv\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Bot\venv\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Bot\venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Bot\venv\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Bot\venv\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\aswan218\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Bot\Binance Detect Moonings.py", line 585, in <module>
    orders, last_price, volume = buy()
  File "C:\Bot\Binance Detect Moonings.py", line 292, in buy
    volume, last_price = convert_volume()
  File "C:\Bot\Binance Detect Moonings.py", line 253, in convert_volume
    volatile_coins, number_of_coins, last_price = wait_for_price()
  File "C:\Bot\Binance Detect Moonings.py", line 146, in wait_for_price
    get_price()
  File "C:\Bot\Binance Detect Moonings.py", line 101, in get_price
    prices = client.get_all_tickers()
  File "C:\Bot\venv\lib\site-packages\binance\client.py", line 437, in get_all_tickers
    return self._get('ticker/price', version=self.PRIVATE_API_VERSION)
  File "C:\Bot\venv\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Bot\venv\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Bot\venv\lib\site-packages\binance\client.py", line 196, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "C:\Bot\venv\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Bot\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Bot\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Bot\venv\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Process finished with exit code 1

**Comment by lavaground** [comment]
What comes to my mind:
Did you run more than one bot and/or with the same api key?
Are you using a wireless internet connection (WiFi or Mobile)?
Are you experiencing timeouts with your internet connection?
Is your system time synchronized correctly?
How did you run the bot?

It could also be on Binance that you got disconnected.

**Comment by FreshLondon** [comment]
Are you in the USA?

**Comment by MrPr0xY** [comment]
I am overseas right now.
Will test again when I get to US

**Comment by FreshLondon** [comment]
Was the bot functioning seconds before (above this error)?

If not, maybe you're using a Binance US account outside. Haven't tried it, Binance US has some weird resrictions!
Are you on Binance US or global version?

**Comment by RyoSaitoOp3** [comment]
I faced the same error. I suspect this is because this bot reuses `client` after binance server timeout. See [this StackOverflow thread](https://stackoverflow.com/questions/56519640/cant-continue-a-program-when-binance-apiconnection-error-occured/56554869#56554869).
