### ISSUE TITLE
several problems with new ver

### ISSUE THREAD

**Issue by twofacednine380** [CyberPunkMetalHead/Binance-volatility-trading-bot#157]
Traceback (most recent call last):
  File "/home/Binance-volatility-trading-bot-main/helpers/handle_creds.py", line 19, in test_api_key
    client.get_account()
  File "/usr/local/lib/python3.9/dist-packages/binance/client.py", line 1767, in get_account
    return self._get('account', True, data=params)
  File "/usr/local/lib/python3.9/dist-packages/binance/client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/usr/local/lib/python3.9/dist-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request is outside of the recvWindow.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Binance-volatility-trading-bot-main/bot.py", line 524, in <module>
    api_ready, msg = test_api_key(client, BinanceAPIException)
  File "/home/Binance-volatility-trading-bot-main/helpers/handle_creds.py", line 39, in test_api_key
    msg += e
TypeError: can only concatenate str (not "BinanceAPIException") to str

**Comment by ShogunMan** [comment]
Your linux version seems not up to date. We are not using the test API.
