### ISSUE TITLE
wait_for_price(): volatile_coins not a subset of last_price

### ISSUE THREAD

**Issue by chadpete1989** [CyberPunkMetalHead/Binance-volatility-trading-bot#162]
Consistently erroring out at line 274 in Binance Detect Moonings.py . with Key Error. Occurs when market conditions are good in attempt to initiate buys:
Traceback (most recent call last):
  File ".\Binance Detect Moonings.py", line 600, in <module>
    orders, last_price, volume = buy()
  File ".\Binance Detect Moonings.py", line 300, in buy
    volume, last_price = convert_volume()
  File ".\Binance Detect Moonings.py", line 281, in convert_volume
    volume[coin] = float(QUANTITY / float(last_price[coin]['price']))
KeyError: 'ADAUSDT'

I printed out volatile_coins and last_price . Shoudn't volatile_coins be a subset of last_price? Majority of coins here do not exist in last_price.

e.g.

[2021-05-31 11:57:44] Working...Session profit:0.00% Est:$0.00
[2021-05-31 11:57:44] Signalsample:BCHUSDT First 14 Second 15
[2021-05-31 11:57:44] Signalsample: Signal detected on BCHUSDT
[2021-05-31 11:57:44] Signalsample:UNIUSDT First 14 Second 15
[2021-05-31 11:57:44] Signalsample: Signal detected on UNIUSDT
[2021-05-31 11:57:44] External signal received on BTCUSDT, calculating volume in USDT
[2021-05-31 11:57:44] External signal received on ETHUSDT, calculating volume in USDT
[2021-05-31 11:57:44] External signal received on BNBUSDT, calculating volume in USDT
[2021-05-31 11:57:44] External signal received on ADAUSDT, calculating volume in USDT
[2021-05-31 11:57:44] External signal received on DOTUSDT, calculating volume in USDT
[2021-05-31 11:57:44] External signal received on BCHUSDT, calculating volume in USDT
[2021-05-31 11:57:44] <class 'dict'>
[2021-05-31 11:57:44] vc 0 : BTCUSDT
[2021-05-31 11:57:44] vc 1 : ETHUSDT
[2021-05-31 11:57:44] vc 2 : BNBUSDT
[2021-05-31 11:57:44] vc 3 : ADAUSDT
[2021-05-31 11:57:44] vc 4 : DOTUSDT
[2021-05-31 11:57:44] vc 5 : BCHUSDT
[2021-05-31 11:57:45] Signalsample:LTCUSDT First 17 Second 17
[2021-05-31 11:57:45] Signalsample: Signal detected on LTCUSDT
[2021-05-31 11:57:45] <class 'dict'>
[2021-05-31 11:57:45] lp 0 : BNBUSDT
[2021-05-31 11:57:45] lp 1 : BTCUSDT
[2021-05-31 11:57:45] lp 2 : ETHUSDT
[2021-05-31 11:57:45] lp 3 : LTCUSDT
[2021-05-31 11:57:45] lp 4 : XRPUSDT
[2021-05-31 11:57:45] Signalsample:LINKUSDT First 11 Second 15
[2021-05-31 11:57:45] Signalsample:SOLUSDT First 12 Second 14
[2021-05-31 11:57:45] Signalsample: Signal detected on SOLUSDT
[2021-05-31 11:57:46] Signalsample:ETCUSDT First 14 Second 15
[2021-05-31 11:57:46] Signalsample: Signal detected on ETCUSDT
[2021-05-31 11:57:46] Signalsample:FILUSDT First 17 Second 16
[2021-05-31 11:57:46] Signalsample: Signal detected on FILUSDT
[2021-05-31 11:57:47] Signalsample:EOSUSDT First 13 Second 15
[2021-05-31 11:57:47] Signalsample: Signal detected on EOSUSDT
[2021-05-31 11:57:47] <class 'dict'>
[2021-05-31 11:57:47] lp 0 : BNBUSDT
[2021-05-31 11:57:47] lp 1 : BTCUSDT
[2021-05-31 11:57:47] lp 2 : ETHUSDT
[2021-05-31 11:57:47] lp 3 : LTCUSDT
[2021-05-31 11:57:47] lp 4 : XRPUSDT
[2021-05-31 11:57:47] Signalsample:XMRUSDT First 16 Second 17
[2021-05-31 11:57:47] Signalsample: Signal detected on XMRUSDT
[2021-05-31 11:57:47] Signalsample: Max signal by LTCUSDT at 17 on shortest timeframe
[2021-05-31 11:57:47] Signalsample: 14 coins above 12 treshold on both timeframes. Waiting 1 minutes for next analysis
[2021-05-31 11:57:47] <class 'dict'>
[2021-05-31 11:57:47] lp 0 : BNBUSDT
[2021-05-31 11:57:47] lp 1 : BTCUSDT
[2021-05-31 11:57:47] lp 2 : ETHUSDT
[2021-05-31 11:57:47] lp 3 : LTCUSDT
[2021-05-31 11:57:47] lp 4 : XRPUSDT
[2021-05-31 11:57:48] <class 'dict'>
[2021-05-31 11:57:48] lp 0 : BNBUSDT
[2021-05-31 11:57:48] lp 1 : BTCUSDT
[2021-05-31 11:57:48] lp 2 : ETHUSDT
[2021-05-31 11:57:48] lp 3 : LTCUSDT
[2021-05-31 11:57:48] lp 4 : XRPUSDT
Traceback (most recent call last):
  File ".\Binance Detect Moonings.py", line 600, in <module>
    orders, last_price, volume = buy()
  File ".\Binance Detect Moonings.py", line 300, in buy
    volume, last_price = convert_volume()
  File ".\Binance Detect Moonings.py", line 281, in convert_volume
    volume[coin] = float(QUANTITY / float(last_price[coin]['price']))
KeyError: 'ADAUSDT'

Here is my config:
{
    "script_options": {
        "TEST_MODE": true,
        "LOG_TRADES": true,
        "LOG_FILE": "trades.txt",        
        "AMERICAN_USER": true
    },
    "trading_options": {
        "PAIR_WITH": "USDT",
        "QUANTITY": 15,
        "FIATS": [
            "EURUSDT",
            "GBPUSDT",
            "JPYUSDT",
            "USDUSDT",
            "DOWN",
            "UP"
        ],
        "MAX_COINS": 7,
        "TIME_DIFFERENCE": 1,
        "RECHECK_INTERVAL": 60,
        "CHANGE_IN_PRICE": 10,
        "STOP_LOSS": 0.18,
        "TAKE_PROFIT": 0.6,
        "CUSTOM_LIST": true,
        "TICKERS_LIST": "tickers.txt",
        "USE_TRAILING_STOP_LOSS": false,
        "TRAILING_STOP_LOSS": 0.4,
        "TRAILING_TAKE_PROFIT": 0.1,
        "TRADING_FEE": 0.075,
        "SIGNALLING_MODULES": [
            "pausebotmod",
            "signalsamplemod"
        ]
    }
}

**Comment by aeickmeyer** [comment]
Delete coins_bought.json and trades.txt before you start the script.

**Comment by chadpete1989** [comment]
I have tried that, still same behiavor.

**Comment by chadpete1989** [comment]
To add, this behavior is with TESTNET and not MAINNET

**Comment by ShogunMan** [comment]
Your tickers lists are not correctly set up. Furter we do not use testnet, but have a test mode on mainnet.

**Comment by m3a4s** [comment]
when Market looks ok, bot is running...

this error comes out:

Traceback (most recent call last):
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 597, in
orders, last_price, volume = buy()
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 294, in buy
volume, last_price = convert_volume()
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 255, in convert_volume
volatile_coins, number_of_coins, last_price = wait_for_price()
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 139, in wait_for_price
if historical_prices[hsp_head]['BNB' + PAIR_WITH]['time'] > datetime.now() - timedelta(minutes=float(TIME_DIFFERENCE / RECHECK_INTERVAL)):
KeyError: 'BNBUSDT'

what's the solution PLS ?

**Comment by aeickmeyer** [comment]
Make a new tickers.txt with the code that under this text. (save it in a file called e.g. "write_binance_coins.py"  and run it. (sorry only german comments - no time to translate).
Than replace BNB in 
if historical_prices[hsp_head]['BNB' + PAIR_WITH]['time'] > datetime.now() - timedelta(minutes=float(TIME_DIFFERENCE / RECHECK_INTERVAL)):
With LTC. Hope that helps...

Allu



START py code:
'''
Stand: 15.09.2021 - Auszuschließende Coins hinzugefügt -ae
                  - Erstellt jetzt auch tickers.txt
                  - Holt die Währungen direkt von der url
24.08.2021 - Erste Version -  ae

Aktualisieren von binance_coins_cyberpunk.txt (Die Datei wird gebraucht um die url zu binance zusammenzubauen)
Da immer wieder coins dazukommen muss diese Datei gelegentlich aktualisiert werden.
Vorgehen:
Alle Währungspaare aus binance holen
Die Ausgabe in "binance_coins.json" abspeichern.
Diese Datei wird hier dann nach dem Suchstring z.B. "USDT" durchsucht.
Alle Suchstringpaare  (z.B. BTCUSDT)  werden abzüglich selbst gekaufter Coins im Portfolio, Stabelcoins
und Währungspaare etc. nach binance_coins_cyberpunk.txt und tickers.txt geschrieben.
Binance_Detect_Moonings.py arbeitet dann nur noch mit diesen Währungspaaren wenn   CUSTOM_LIST: true gesetzt ist!

'''
import json
import requests
import time
import urllib
import os


def write_binance_tickers():
    tickersdatei = "tickers.txt"  # von Trader benutzte whitelist datei
    binance_asset_file_path = 'binance_coins.json'  # input Erzeugung siehe oben
    binance_asset_output = 'binance_coins_cyberpunk.txt'  # output
    binance_Coins = {}
    SuchString = "USDT"  # ALle Paare mit dieser Währung
    SuchStringLaenge = len(SuchString)
    CoinNameLaenge = 0
    # Zunächst ALLE  aktuellen coins von binance abholen holen
    Assetfile = 'binance_coins.json'
    # Assetfile löschen
    open(Assetfile, 'w').close()
    Boersenurl = 'https://api.binance.com/api/v1/ticker/allPrices'  # Augabe aller ticker der Boerse
    r = requests.get(Boersenurl, allow_redirects=False)  # Abruf
    time.sleep(2)  # Wir geben der Seite Gelegenheit sich aufzubauen und befüllen dann die json datei
    output = open(Assetfile, 'wb').write(r.content)
    # binance_asset_output leeren
    open(binance_asset_output, 'w').close()
    open(tickersdatei, 'w').close()
    if os.path.isfile(binance_asset_file_path) and os.stat(binance_asset_file_path).st_size != 0:
        with open(binance_asset_file_path) as file:
            binance_Coins = json.load(file)
    # AUSZUSCHLIESSENDE Assets
    # Coins im Partfolio die ausserhalb des bot gekauft wurden und ausgeschlossen werden!
    MyCoins = ["VTHO", "SOL"]
    # Währungen ausschließen'
    ExcludeCoins = ["BNB", "EUR", "GBP", "JPY", "USD"]
    # Stablecoins ausschließen
    Stablecoins = ["USDT", "USDC", "DAI", "MKR"]
    ExcludeCoins += MyCoins  # MyCoins an ExcludeCoins anhängen
    ExcludeCoins += Stablecoins  # Stablecoins an ExcludeCoins anhängen
    output = open(binance_asset_output, 'a')  # 'a' steht für appand!
    for coin in binance_Coins:
        CoinSymbol = coin['symbol']
        # print(CoinSymbol)
        #  TheMessage = f"{CoinSymbol}\n"
        Splitstring = CoinSymbol[-SuchStringLaenge:]
        if SuchString == Splitstring:
            CoinName = CoinSymbol[0:-SuchStringLaenge]
            CoinNameLaenge = len(CoinName)
            # Filter: Keine Währungspaare mit "UP"/ "DOWN" oder in der Liste ExcludeCoins
            if (not CoinName[-2:] == "UP"):
                if (CoinName not in ExcludeCoins):
                    if (CoinNameLaenge > 4):
                        TestCoinName = CoinName[-4:]
                        if (not TestCoinName == "DOWN") and (not TestCoinName == "BULL") and (not TestCoinName == "BEAR"):
                            TheMessage = f"{CoinName}\n"
                            output.write(TheMessage)
                    else:
                        TheMessage = f"{CoinName}\n"
                        output.write(TheMessage)

    # Kopieren in tickers.txt Dateiname
    output.close()
    input = open(binance_asset_output, 'r')  # 'r' steht für read!
    output = open(tickersdatei, 'w')
    with input as f:
        with output as f1:
            for line in f:
                # if "ROW" in line: Selektierung
                f1.write(line)

    input.close()
    output.close()
    return


if __name__ == '__main__':
    write_binance_tickers()

:END py code

**Comment by m3a4s** [comment]
thank you sir for your reply 
i tried your code and this comes out to me :

Traceback (most recent call last):
  File "c:/Users/pc/Desktop/BINC. Bot/Qiuck/write_binance_coins.py", line 86, in <module>
    if name == 'main':
NameError: name 'name' is not defined
PS C:\Users\pc\Desktop\BINC. Bot\Qiuck> 


i wish sir if you send me this code as py file , not text .
i am a beginner , i have been working on your code for the last 2 hours , but still comes a few problems to me , so i wish you send the code as python format.

best regards

**Comment by aeickmeyer** [comment]
As a beginner be warned!
Do not play around with your real money!
Use testnet instead!

Best regards





Am Mo., 27. Sept. 2021 um 06:01 Uhr schrieb Moath Sawi
***@***.***>:
