### ISSUE TITLE
Binance API exception about computer timezone?

### ISSUE THREAD

**Issue by Arcea** [CyberPunkMetalHead/Binance-volatility-trading-bot#165]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Binance-volatility-trading-bot-main\helpers\handle_creds.py", line 19, in test_api_key
    client.get_account()
  File "C:\Users\user\Desktop\Binance-volatility-trading-bot-main\.venv\lib\site-packages\binance\client.py", line 1767, in get_account
    return self._get('account', True, data=params)
  File "C:\Users\user\Desktop\Binance-volatility-trading-bot-main\.venv\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\user\Desktop\Binance-volatility-trading-bot-main\.venv\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\user\Desktop\Binance-volatility-trading-bot-main\.venv\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "C:\Users\user\Desktop\Binance-volatility-trading-bot-main\.venv\lib\site-packages\binance\client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Binance Detect Moonings.py", line 524, in <module>
    api_ready, msg = test_api_key(client, BinanceAPIException)
  File "C:\Users\user\Desktop\Binance-volatility-trading-bot-main\helpers\handle_creds.py", line 39, in test_api_key
    msg += e
TypeError: can only concatenate str (not "BinanceAPIException") to str

---
This occurs when executing Moonings.py.

**Comment by ShogunMan** [comment]
Please do not put up issues that are described and solved in FAQ and setupguide. RTFM!
