### ISSUE TITLE
socket.timout the read operation has timed out

### ISSUE THREAD

**Issue by wo-mick** [CyberPunkMetalHead/Binance-volatility-trading-bot#173]
```
Traceback (most recent call last):
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\urllib3\connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\urllib3\connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bot\Binance-volatility-trading-bot-main\bdm.py", line 592, in <module>
    orders, last_price, volume = buy()
  File "C:\bot\Binance-volatility-trading-bot-main\bdm.py", line 292, in buy
    volume, last_price = convert_volume()
  File "C:\bot\Binance-volatility-trading-bot-main\bdm.py", line 253, in convert_volume
    volatile_coins, number_of_coins, last_price = wait_for_price()
  File "C:\bot\Binance-volatility-trading-bot-main\bdm.py", line 136, in wait_for_price
    pause_bot()
  File "C:\bot\Binance-volatility-trading-bot-main\bdm.py", line 231, in pause_bot
    get_price(True)
  File "C:\bot\Binance-volatility-trading-bot-main\bdm.py", line 101, in get_price
    prices = client.get_all_tickers()
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\binance\client.py", line 437, in get_all_tickers
    return self._get('ticker/price', version=self.PRIVATE_API_VERSION)
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\binance\client.py", line 196, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\bot\Binance-volatility-trading-bot-main\.venv\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
```

**Comment by shanemcgray** [comment]
### I'm getting the same thing. 

[2021-06-03 20:38:37] pausebotmod: Market not looking too good, bot paused from buying 14/7 Waiting 1 minutes for next market checkup
[2021-06-03 20:38:44] Paused...Session profit:0.00% Est:$0.00
[2021-06-03 20:38:56] Not holding any coins
[2021-06-03 20:39:37] pausebotmod: Market not looking too good, bot paused from buying 14/7 Waiting 1 minutes for next market checkup
Traceback (most recent call last):
  File "/home/shane/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/shane/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shane/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/shane/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/shane/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/shane/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/shane/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/shane/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/shane/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.binance.us', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shane/BinBot/Binance Detect Moonings.py", line 592, in <module>
    orders, last_price, volume = buy()
  File "/home/shane/BinBot/Binance Detect Moonings.py", line 292, in buy
    volume, last_price = convert_volume()
  File "/home/shane/BinBot/Binance Detect Moonings.py", line 253, in convert_volume
    volatile_coins, number_of_coins, last_price = wait_for_price()
  File "/home/shane/BinBot/Binance Detect Moonings.py", line 136, in wait_for_price
    pause_bot()
  File "/home/shane/BinBot/Binance Detect Moonings.py", line 229, in pause_bot
    coins_sold = sell_coins()
  File "/home/shane/BinBot/Binance Detect Moonings.py", line 357, in sell_coins
    last_price = get_price(False) # don't populate rolling window
  File "/home/shane/BinBot/Binance Detect Moonings.py", line 101, in get_price
    prices = client.get_all_tickers()
  File "/home/shane/.local/lib/python3.9/site-packages/binance/client.py", line 565, in get_all_tickers
    return self._get('ticker/price', version=self.PRIVATE_API_VERSION)
  File "/home/shane/.local/lib/python3.9/site-packages/binance/client.py", line 365, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/home/shane/.local/lib/python3.9/site-packages/binance/client.py", line 328, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/shane/.local/lib/python3.9/site-packages/binance/client.py", line 308, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/home/shane/.local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/shane/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/shane/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/shane/.local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.binance.us', port=443): Read timed out. (read timeout=10)

**Comment by Tetdoss** [comment]
Hello, I've got the same issue !

**Comment by getsec** [comment]
Fixed in latest release
