### ISSUE TITLE
Conversion error crashing

### ISSUE THREAD

**Issue by gmcmillan82** [CyberPunkMetalHead/Binance-volatility-trading-bot#174]
So I've been running the script for the last few days and it appears to run okay for some time. However I often find it stopped with the following message:

```
[2021-06-02 15:22:11] External signal received on XRPUSDT, calculating volume in EUR
Traceback (most recent call last):
  File "Binance Detect Moonings.py", line 592, in <module>
    orders, last_price, volume = buy()
  File "Binance Detect Moonings.py", line 292, in buy
    volume, last_price = convert_volume()
  File "Binance Detect Moonings.py", line 274, in convert_volume
    volume[coin] = float(QUANTITY / float(last_price[coin]['price']))
KeyError: 'XRPUSDT'
```

I am using EUR as my FIAT pair in the config.yml.

The script is running on Python 3.8.5 (in venv) on Ubuntu 20.04 server.

[config.tar.gz](https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/files/6585750/config.tar.gz)

**Comment by ShogunMan** [comment]
Not an issue, check faq, docs and discord.
