### ISSUE TITLE
Recently listed coins fails to trade

### ISSUE THREAD

**Issue by toyan** [CyberPunkMetalHead/Binance-volatility-trading-bot#186]
[2021-06-07 05:59:01] pausebotmod: Market not looking too good, bot paused from buying 10/7 Waiting 1 minutes for next market checkup
[2021-06-07 06:00:02] pausebotmod: Market not looking too good, bot paused from buying 9/7 Waiting 1 minutes for next market checkup
[2021-06-07 06:01:02] pausebotmod: Market looks ok, bot is running 6/7 Waiting 1 minutes for next market checkup
[2021-06-07 06:01:12] Resuming buying due to change in market conditions, total sleep time: 0:03:05
[2021-06-07 06:01:12] Working...Session profit:15.62% Est:$3.12
Traceback (most recent call last):
  File "Binance Detect Moonings.py", line 592, in <module>
    orders, last_price, volume = buy()
  File "Binance Detect Moonings.py", line 292, in buy
    volume, last_price = convert_volume()
  File "Binance Detect Moonings.py", line 253, in convert_volume
    volatile_coins, number_of_coins, last_price = wait_for_price()
  File "Binance Detect Moonings.py", line 152, in wait_for_price
    min_price = min(historical_prices, key = lambda x: float("inf") if x is None else float(x[coin]['price']))
  File "Binance Detect Moonings.py", line 152, in <lambda>
    min_price = min(historical_prices, key = lambda x: float("inf") if x is None else float(x[coin]['price']))
KeyError: 'ATAUSDT'

**Comment by koshrf** [comment]
It is a new coin that binance added, just edit tickers.txt and add it. Or blacklist it.

**Comment by toyan** [comment]
Why to blacklist rockets?! I want to catch it and fly to the moon, accordingly with name of the app "Binance Detect Moonings.py".
I use "CUSTOM_LIST: False" in config, but 'ATAUSDT' fiers ~4500% with few hours without me. ))

**Comment by koshrf** [comment]
> Why to blacklist rockets?! I want to catch them and fly to the moon, accordingly with name of the app "Binance Detect Moonings.py".
> I use "CUSTOM_LIST: False" in config, but 'ATAUSDT' fiers ~4500% with few hours without me. ))

This isn't the place for this, but just so you know it shows 4500% because it launched today at 0 value, got a micro peak of 4.5$ (just few sells) then crashed to 1.6$. So, no, it didn't moon, that's what happen when new coins enter the exchanges and if you had put money on it you would have surely lose it.

This app need an option to ban new coins that enter the exchange for a certain of period, most bots have it so it prevents people from losing money on day 1.

**Comment by getsec** [comment]
@koshrf is right.

**Comment by m3a4s** [comment]
when Market looks ok, bot is running...

this error comes out:

Traceback (most recent call last):
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 597, in
orders, last_price, volume = buy()
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 294, in buy
volume, last_price = convert_volume()
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 255, in convert_volume
volatile_coins, number_of_coins, last_price = wait_for_price()
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 139, in wait_for_price
if historical_prices[hsp_head]['BNB' + PAIR_WITH]['time'] > datetime.now() - timedelta(minutes=float(TIME_DIFFERENCE / RECHECK_INTERVAL)):
KeyError: 'BNBUSDT'

what's the solution PLS ?
