### ISSUE TITLE
Pausebotmod stop working if there is a connection time out.

### ISSUE THREAD

**Issue by koshrf** [CyberPunkMetalHead/Binance-volatility-trading-bot#196]
The error is similar when there was an error connecting to binance, but now it is with scanner.tradingview.com and when it happens it disable pausebotmod, if the session was stopped because a bad market it never changes status because the mod is dead.

HTTPSConnectionPool(host='scanner.tradingview.com', port=443): Max retries exceeded with url: /crypto/scan (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff0651049e8>, 'Connection to scanner.tradingview.com timed out. (connect timeout=10)'))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/koshrf/binance/Binance-volatility-trading-bot/pausebotmod.py", line 48, in do_work
    paused = analyze()
  File "/home/koshrf/binance/Binance-volatility-trading-bot/pausebotmod.py", line 33, in analyze
    ma_sell = analysis.moving_averages['SELL']
AttributeError: 'dict' object has no attribute 'moving_averages'

**Comment by whit3he4d** [comment]
same her
