### ISSUE TITLE
Market looks ok 

### ISSUE THREAD

**Issue by m3a4s** [CyberPunkMetalHead/Binance-volatility-trading-bot#217]
when Market looks ok, bot is running...

this error comes out:

Traceback (most recent call last):
  File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 597, in <module>
    orders, last_price, volume = buy()
  File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 294, in buy
    volume, last_price = convert_volume()
  File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 255, in convert_volume
    volatile_coins, number_of_coins, last_price = wait_for_price()
  File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 139, in wait_for_price
    if historical_prices[hsp_head]['BNB' + PAIR_WITH]['time'] > datetime.now() - timedelta(minutes=float(TIME_DIFFERENCE / RECHECK_INTERVAL)):
KeyError: 'BNBUSDT'

**what's the solution ?**

**Comment by Hedgenious** [comment]
Have you found the answer?

**Comment by ddkargas** [comment]
You  must have  BNB symbol in files tickers & signalsample, after this ishould work!

**Comment by sungseh** [comment]
Make sure you have BNB as one of the tickers in tickers.txt. It worked for me
