### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time

### ISSUE THREAD

**Issue by mwerre1** [CyberPunkMetalHead/Binance-volatility-trading-bot#28]
APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

**Comment by ErenYuksel-RMIT** [comment]
if you're on windows, syncing with `time.nist.gov` solved the issue for me.

**Comment by Eugnis** [comment]
If you run in WSL2, [it's known bug](https://stackoverflow.com/questions/65086856/wsl2-clock-is-out-of-sync-with-windows). Run `sudo hwclock -s`
Fixed with latest windows 10 insiders build

**Comment by gabtech722** [comment]
Testing bot on testnet and just got this error:

TRXUSDT has gained 15.023% in the last 5 minutes, calculating volume in USDT
 preparing to buy 698.8 TRXUSDT
Traceback (most recent call last):
  File "/initrd/mnt/dev_save/BUGHUNTER/BINANCE/Binance-volatility-trading-bot/Binance-Detect.py", line 356, in <module>
    orders, last_price, volume = buy()
  File "/initrd/mnt/dev_save/BUGHUNTER/BINANCE/Binance-volatility-trading-bot/Binance-Detect.py", line 228, in buy
    test_order = client.create_test_order(symbol=coin, side='BUY', type='MARKET', quantity=volume[coin])
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 1578, in create_test_order
    return self._post('order/test', True, data=params)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

**Comment by L0Y4L** [comment]
Same for me @gabtech722

**Comment by m3a4s** [comment]
when Market looks ok, bot is running...

this error comes out:

Traceback (most recent call last):
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 597, in
orders, last_price, volume = buy()
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 294, in buy
volume, last_price = convert_volume()
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 255, in convert_volume
volatile_coins, number_of_coins, last_price = wait_for_price()
File "c:/Users/pc/Desktop/TradingTry/Binance Detect Moonings.py", line 139, in wait_for_price
if historical_prices[hsp_head]['BNB' + PAIR_WITH]['time'] > datetime.now() - timedelta(minutes=float(TIME_DIFFERENCE / RECHECK_INTERVAL)):
KeyError: 'BNBUSDT'

what's the solution ?
