### ISSUE TITLE
IndexError: list index out of range for QUANTITY=10

### ISSUE THREAD

**Issue by erathia65** [CyberPunkMetalHead/Binance-volatility-trading-bot#4]
Script is vanilla except for QUANTITY=10, here's the traceback:

```
Traceback (most recent call last):
  File "bot.py", line 284, in <module>
    update_porfolio(orders, last_price, volume)
  File "bot.py", line 226, in update_porfolio
    'symbol': orders[coin][0]['symbol'],
IndexError: list index out of range
```

Last echo from the script: 

` preparing to buy 0.089 WNXMUSDT `
 
 The script does not close the order after this.

**Comment by erathia65** [comment]
Closed: Duplicate
