### ISSUE TITLE
Binance API Exception Filter Failure: MIN_NOTIONAL

### ISSUE THREAD

**Issue by Maxxxel** [CyberPunkMetalHead/Binance-volatility-trading-bot#47]
```python
BTCUSDT has gained 8.354% in the last 5 minutes, calculating volume in USDT
 preparing to buy 0.000162 BTCUSDT
Traceback (most recent call last):
  File "Mooning.py", line 335, in <module>
    orders, last_price, volume = buy()
  File "Mooning.py", line 209, in buy
    test_order = client.create_test_order(symbol=coin, side='BUY', type='MARKET', quantity=volume[coin])
  File "/home/maxxxel/.local/lib/python3.7/site-packages/binance/client.py", line 1762, in create_test_order
    return self._post('order/test', True, data=params)
  File "/home/maxxxel/.local/lib/python3.7/site-packages/binance/client.py", line 368, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/maxxxel/.local/lib/python3.7/site-packages/binance/client.py", line 328, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/maxxxel/.local/lib/python3.7/site-packages/binance/client.py", line 309, in _request
    return self._handle_response(self.response)
  File "/home/maxxxel/.local/lib/python3.7/site-packages/binance/client.py", line 318, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: MIN_NOTIONAL
```

**Comment by GitHub-Leon** [comment]
This error occurs, when you couldn't buy the minimal amount necessary to do the trade. You should trade with at least 15$, from my experience, to stop this error from occuring

**Comment by CyberPunkMetalHead** [comment]
@Maxxxel see issue #5 or call `info = client.get_symbol_info('BTCUSDT') `and look for the 'minQty' key to find the minimum tradable amount for your pair.
