### ISSUE TITLE
APIError  Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by getsec** [CyberPunkMetalHead/Binance-volatility-trading-bot#48]
```
TRXUSDT has gained 56.956% in the last 5 minutes, calculating volume in USDT
 preparing to buy 707.9 TRXUSDT
Traceback (most recent call last):
  File "script.py", line 343, in <module>
    orders, last_price, volume = buy()
  File "script.py", line 228, in buy
    test_order = client.create_test_order(symbol=coin, side='BUY', type='MARKET', quantity=volume[coin])
  File "/home/ngetty/Binance-volatility-trading-bot/venv/lib/python3.8/site-packages/binance/client.py", line 1578, in create_test_order
    return self._post('order/test', True, data=params)
  File "/home/ngetty/Binance-volatility-trading-bot/venv/lib/python3.8/site-packages/binance/client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/ngetty/Binance-volatility-trading-bot/venv/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/ngetty/Binance-volatility-trading-bot/venv/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/home/ngetty/Binance-volatility-trading-bot/venv/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.
```

**Comment by olesgeras** [comment]
https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/issues/28

**Comment by CyberPunkMetalHead** [comment]
Thanks @olesgeras, closing this issue
