### ISSUE TITLE
Removing BNB from the tickers results in a crash

### ISSUE THREAD

**Issue by mindflvx** [CyberPunkMetalHead/Binance-volatility-trading-bot#75]
While looking at #72 also noticed this if custom ticker list is enabled, console output:

```
Traceback (most recent call last):
  File "D:\Python\Binance Detect Moonings.py", line 398, in <module>
    orders, last_price, volume = buy()
  File "D:\Python\Binance Detect Moonings.py", line 241, in buy
    volume, last_price = convert_volume()
  File "D:\Python\Binance Detect Moonings.py", line 202, in convert_volume
    volatile_coins, number_of_coins, last_price = wait_for_price()
  File "D:\Python\Binance Detect Moonings.py", line 152, in wait_for_price
    while initial_price['BNB' + PAIR_WITH]['time'] > datetime.now() - timedelta(seconds=TIME_DIFFERENCE):
KeyError: 'BNBUSDT'
```

**Comment by ShogunMan** [comment]
Yes, BNB must be in the tickerlist for the price check function to work.

**Comment by mindflvx** [comment]
Yes, makes sense after reviewing the code. 

I guess it would be nice if app could exit gracefully but it seems like a no-issue so closing this now.
