### ISSUE TITLE
Lost connection...

### ISSUE THREAD

**Issue by Balduxnet** [CyberPunkMetalHead/Binance-volatility-trading-bot#83]
if the connection is lost the bot stops, please handle the exception.
Thanks!

**Comment by phroton** [comment]
what error message did you get?

**Comment by Balduxnet** [comment]
checking TP/SL...
Traceback (most recent call last):
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Baldux\Anaconda2020.11\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\Baldux\Anaconda2020.11\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Baldux\Anaconda2020.11\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Baldux\Anaconda2020.11\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Baldux\Anaconda2020.11\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Baldux\Anaconda2020.11\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\urllib3\util\retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\urllib3\connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\urllib3\connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Binance Detect Moonings.py", line 396, in <module>
    orders, last_price, volume = buy()
  File "Binance Detect Moonings.py", line 157, in buy
    volume, last_price = convert_volume()
  File "Binance Detect Moonings.py", line 117, in convert_volume
    volatile_coins, number_of_coins, last_price = wait_for_price()
  File "Binance Detect Moonings.py", line 70, in wait_for_price
    coins_sold = sell_coins()
  File "Binance Detect Moonings.py", line 211, in sell_coins
    last_price = get_price()
  File "Binance Detect Moonings.py", line 45, in get_price
    prices = client.get_all_tickers()
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\binance\client.py", line 437, in get_all_tickers
    return self._get('ticker/price', version=self.PRIVATE_API_VERSION)
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\binance\client.py", line 196, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Baldux\Anaconda2020.11\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

**Comment by phroton** [comment]
#84

**Comment by chenzo6** [comment]
I have the same problem, maybe if we could set the timeout for 20 seconds is better, but anyway the bot should not crash after a connection lost...

**Comment by agustincastanio** [comment]
Same here.

> [2021-05-19 08:37:03] Signalsample: Max signal by QTUMUSDT at 18 on shortest timeframe
[2021-05-19 08:37:03] Signalsample: No coins above 18 threshold on both timeframes
[2021-05-19 08:37:03] Signalsample: Waiting 4 minutes for next analysis
[2021-05-19 08:41:03] Signalsample: Analyzing 90 coins
[2021-05-19 08:41:13] Signalsample:
[2021-05-19 08:41:13] Exception:
[2021-05-19 08:41:13] HTTPSConnectionPool(host='scanner.tradingview.com', port=443): Read timed out. (read timeout=10)
[2021-05-19 08:41:13] Coin: 1INCHUSDT
[2021-05-19 08:41:13] First handler: <tradingview_ta.main.TA_Handler object at 0x7fd9ac94e590>
[2021-05-19 08:41:13] Second handler: <tradingview_ta.main.TA_Handler object at 0x7fd9ac94e510>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Binance-volatility-trading-bot/signalsamplemod.py", line 91, in do_work
    signal_coins = analyze(pairs)
  File "/root/Binance-volatility-trading-bot/signalsamplemod.py", line 62, in analyze
    first_tacheck = first_analysis.summary['BUY']
AttributeError: 'dict' object has no attribute 'summary'

**Comment by FreshLondon** [comment]
> Same here.
> > AttributeError: 'dict' object has no attribute 'summary'

this is a different error

**Comment by birkschmithuesen** [comment]
Having the same problem. 
Have another bot running, that could handle the exception and continue running smoothly.
My code is running on a hosted Server, so it can'ät be the problem of my private internet connection.

**Comment by getsec** [comment]
Fixed in latest release

**Comment by ronastlelobo** [comment]
Facing the same issue .

`Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "D:\tradebot\Binance-volatility-trading-bot\signalsamplemod.py", line 91, in do_work
    signal_coins = analyze(pairs)`

Any fix ?
