### ISSUE TITLE
APIError(code=-1022): Signature for this request is not valid.

### ISSUE THREAD

**Issue by ololobin** [CyberPunkMetalHead/Binance-volatility-trading-bot#86]
```
ETHUSDT has gained 2.025% in the last 30 seconds, calculating volume in USDT
Max movement 2.02% by ETHUSDT from 193.5900 to 197.5100
Preparing to buy 0.07595 ETHUSDT
Traceback (most recent call last):
  File "C:\PYPYPY\Binance-volatility-trading-bot\Binance Detect Moonings.py", line 396, in <module>
    orders, last_price, volume = buy()
  File "C:\PYPYPY\Binance-volatility-trading-bot\Binance Detect Moonings.py", line 168, in buy
    test_order = client.create_test_order(symbol=coin, side='BUY', type='MARKET', quantity=volume[coin])
  File "C:\PYPYPY\venv\lib\site-packages\binance\client.py", line 1578, in create_test_order
    return self._post('order/test', True, data=params)
  File "C:\PYPYPY\venv\lib\site-packages\binance\client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "C:\PYPYPY\venv\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\PYPYPY\venv\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "C:\PYPYPY\venv\lib\site-packages\binance\client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1022): Signature for this request is not valid.

Process finished with exit code 1
```

Default configuration
I checked my access_key and secret_key.

I tried in creds.yml

`  access_key: "my_digits_and_numbers"`
`  secret_key: "my_digits_and_numbers"`
and

`  access_key: my_digits_and_numbers`
`  secret_key: my_digits_and_numbers`

**Comment by ololobin** [comment]
Works fine is added manually

```
    #access_key, secret_key = load_correct_creds(parsed_creds, TESTNET)
    access_key ="y_digits_and_numbers"
    secret_key = "y_digits_and_numbers"
```

**Comment by ShogunMan** [comment]
What if you use ' ' ?

**Comment by usoppu** [comment]
problem is in the handle_creds.py file
it's taking the secret_key from prod
it should look like this:
def load_correct_creds(creds, TESTNET):
    if TESTNET:
        return creds['test']['access_key'], creds['test']['secret_key']
    else:
        return creds['prod']['access_key'], creds['prod']['secret_key']

**Comment by gabtech722** [comment]
As shogunman has noted, using single quotes works just fine.

**Comment by getsec** [comment]
You dont need quotes in the yaml file...
```yml
prod:
  access_key: uUCxxxx
  secret_key: rQd5Rlxxxx

# TEST NET
test:
  access_key: eQxxxx
  secret_key: PBxxx

```

It runs fine.
