### ISSUE TITLE
Did i forgot something? 

### ISSUE THREAD

**Issue by twofacednine380** [CyberPunkMetalHead/Binance-volatility-trading-bot#96]
Traceback (most recent call last):
  File "C:\Users\USER\Documents\binance_bot_v3\Binance-volatility-trading-bot-main\Binance_Detect_Moonings.py", line 396, in <module>
    orders, last_price, volume = buy()
  File "C:\Users\USER\Documents\binance_bot_v3\Binance-volatility-trading-bot-main\Binance_Detect_Moonings.py", line 157, in buy
    volume, last_price = convert_volume()
  File "C:\Users\USER\Documents\binance_bot_v3\Binance-volatility-trading-bot-main\Binance_Detect_Moonings.py", line 117, in convert_volume
    volatile_coins, number_of_coins, last_price = wait_for_price()
  File "C:\Users\PUSER\Documents\binance_bot_v3\Binance-volatility-trading-bot-main\Binance_Detect_Moonings.py", line 66, in wait_for_price
    while initial_price['BNB' + PAIR_WITH]['time'] > datetime.now() - timedelta(seconds=TIME_DIFFERENCE):
KeyError: 'BNBEUR'

(I put api keys only for test)

**Comment by titulebolide** [comment]
Please post your configuration (config.yml) (censor the sensitive data of course)

**Comment by twofacednine380** [comment]
![testnet](https://user-images.githubusercontent.com/68342746/118513469-07160c80-b734-11eb-8d61-10d4983190d1.PNG)

in main is running smoothly

**Comment by titulebolide** [comment]
What do you mean "in main running smoothly?"
Which branch are you on?

**Comment by twofacednine380** [comment]
the main net work fine, the testnet gave the output: "Traceback..."

**Comment by titulebolide** [comment]
I don't really know the underlying logic of the code, but I find this surprising that it tries to swap BNB for EUR

**Comment by twofacednine380** [comment]
yeah, i tried with EUR and with USDT, but still, nevermind, the important is that the mainnet is working! :DD

**Comment by titulebolide** [comment]
Yes absolutely :)
